spring:
  r2dbc:
    url: r2dbc:postgresql://pc1-postgresql-server.postgres.database.azure.com:5432/universidad
    username: cristhiandc
    password: helloWORLD1
    properties:
      sslMode: REQUIRE
server:
  port: 8081
